name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH and pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ '193.110.112.66' }}
          username: ${{ 'vba' }}
          key: ${{ 'copyFromCopy' }}
          script: |
            cd /var/www/vh_my.dipt.ua/html/new/admin_bvv
            git pull
  
